### ISSUE TITLE
Add compilation instructions

### ISSUE THREAD

**Issue by dov** [m5stack/M5EPD#15]
The project is missing compilation instructions. 

I'd like to add some more functionality to the library, e.g. adding libzip, and fribidi, but without compilation instructions, it is not clear how to do that.

**Comment by dov** [comment]
How exactly was this completed? A comment to what was done would be appreciated. Is there a commit ID? There is still e.g. no BUILDING.md file in the repo root dir.

**Comment by icyqwq** [comment]
Which build system are you using?

**Comment by icyqwq** [comment]
Please reopen this issue if needed.
