### ISSUE TITLE
QR Code - Core 1 panic : when size > 26.

### ISSUE THREAD

**Issue by Sarah-C** [m5stack/M5EPD#42]
```

#include <M5EPD.h>

M5EPD_Canvas canvas(&M5.EPD);

int size = 300;

void setup() {
  M5.begin();
  M5.EPD.SetRotation(0);
  M5.EPD.Clear(true);
  canvas.createCanvas(960, 540);
  canvas.qrcode("Test", (960 - size) >> 1, 0, size, 27); // 7 to 40 (over 26 crashes)
  canvas.pushCanvas(0, 0, UPDATE_MODE_DU4);
}

void loop() {
  M5.update();
  delay(100);
}
```
Guru Meditation Error: Core  1 panic'ed (Unhandled debug exception)             
Debug exception reason: Stack canary watchpoint triggered (loopTask)                  
0x400d38d1: qrcode_initBytes at F:\sarah\Documents\Arduino\libraries\M5EPD\src\utility\qrcode.c line 199            
0x400d420a: qrcode_initText at F:\sarah\Documents\Arduino\libraries\M5EPD\src\utility\qrcode.c line 849              
0x400d1c49: M5EPD_Canvas::qrcode(char const*, unsigned short, unsigned short, unsigned short, unsigned char) at F:\sarah\Documents\Arduino\libraries\M5EPD\src\M5EPD_Canvas.cpp line 451               

File qrcode.c:
```
static void bb_initGrid(BitBucket *bitGrid, uint8_t *data, uint8_t size) {
  bitGrid->bitOffsetOrWidth = size;
  bitGrid->capacityBytes = bb_getGridSizeBytes(size);
  bitGrid->data = data;
  memset(data, 0, bitGrid->capacityBytes);  <<< Line 199
}
```

It looks like a memory issue.
We've got 8MB of useable PSRAM on the machine, can someone do some ps_alloc's?

**Comment by rolohaun** [comment]
Hi,

I seen your post on Reedit about making an ereader, I have made one using a different eink screen. The way I did it was use calibre ebook software to word wrap my text file before hand. I just took a free copy of sherlock holms used calibre made it word wrap and put it on the arduino. worked perfect. There are alot of options in the software.
