### ISSUE TITLE
TextWrap doesn't seem to work

### ISSUE THREAD

**Issue by rolohaun** [m5stack/M5EPD#45]
What am I doing wrong

M5.begin();
    M5.EPD.SetRotation(90);
    M5.EPD.Clear(true);
    M5.RTC.begin();
    canvas.createCanvas(540, 960);
    canvas.setTextSize(5);
    canvas.drawString("Connected to WiFi! Test text wrap", 10, 50);
    canvas.pushCanvas(0,0,UPDATE_MODE_DU4);

**Comment by dheijl** [comment]
TextWrap only works with the printxx methods (when enabled).
