### ISSUE TITLE
Please make a new release of this Library

### ISSUE THREAD

**Issue by ubidefeo** [m5stack/M5EPD#46]
as per commit https://github.com/m5stack/M5EPD/commit/2c69459385f6864c85a02918c9a6cbd9206a3668
you have fixed the analog import

the last release was on feb 13 2021...
thank you

ubi

**Comment by Janaboy** [comment]
@Gitshaoxiang is it possible? Could fix a couple of things. 
Thank you in advance.

**Comment by TinyuZhao** [comment]
Okay, I will deal with it as soon as possible.
