### ISSUE TITLE
GT911 - Interrupt disabling causes target reset

### ISSUE THREAD

**Issue by fb87** [m5stack/M5EPD#54]
I am checking **M5EPD** with sample code but target reset right after boot. It's seem to be issue with the Interrupt disabling in GT911 ISR. According to the note from [esp32](https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/Arduino.h#L82) which states **ESP32xx runs FreeRTOS... disabling interrupts can lead to issues, such as Watchdog Timeout**. Since when I was disable the interrupt disabling as bellow, the target didn't reset anymore, kindly check if we can do something better?
```
void ICACHE_RAM_ATTR ___GT911IRQ___()
{
    // noInterrupts();
    gt911_irq_trigger = 1;
    // interrupts();
}
```

**Comment by TinyuZhao** [comment]
Currently in communication with ESP32 about this issue, until then no better solution has been found, please be patient, thanks.
