### ISSUE TITLE
Cannot do simple stuff like invert text or create touch button

### ISSUE THREAD

**Issue by lolren** [m5stack/M5EPD#57]
### Describe the bug

Please add the possibility of creating a touch button and invert the text required for a menu. or create a sketch that shows these features as examples. i think this is the main use of these devices

### To reproduce

nothing to reproduce, is not there!

### Expected behavior

should have been in the examples

### Environment

- OS:
- IDE &IDE Version:
- Repository Version:

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5EPD/issues?q=)
- [X] My report contains all necessary details

**Comment by icyqwq** [comment]
Try setTextColor(0, 15) or setTextColor(15, 0) to invert text color.
And this lib is only for graphic functions, not for UI elements. You could use another UI lib for button or draw it your self.
