### ISSUE TITLE
Issues are closed without being handled

### ISSUE THREAD

**Issue by dov** [m5stack/M5EPD#58]
There was recently a purge of all open issues without any commenting or explanation for why they were closed.

If you are no longer interested in community contributions then you should clearly state that is the case. But letting the community add issues and then arbitrarily closing them is very dishonest.

Let's see how long time it takes for you to close this issue (without comment) as well.

**Comment by icyqwq** [comment]
Those are very outdated issues, and I'm not sure if anyone is still concerned about them, so I closed them. If you need, I can reopen the relevant issues.

Additionally, I provided responses or examples when closing most of the issues.
