### ISSUE TITLE
The README should describe the purpose of this repository

### ISSUE THREAD

**Issue by dov** [m5stack/M5EPD#59]
### Describe the bug

I opened an issue #15 requesting compilation instructions for this repository, and it was closed as not planned. Which makes me wonder what is the purpose of this repository? The README.md does not explain why the repository exists, but is more a product and usage description of the M5 EPD hardware (which is not really the purpose of README.md in github).

I therefore suggest to add to at least to the top the README.md a description of the the purpose of this repo. 

### To reproduce

Open the repo on github and read the README.md file

### Expected behavior

As a comparison of a good description see e.g.:

https://github.com/MHeironimus/ArduinoJoystickLibrary

Which starts with "This library can be used...", and continues with "installation instructions".

### Environment

- OS:
- IDE &IDE Version:
- Repository Version:

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5EPD/issues?q=)
- [X] My report contains all necessary details

**Comment by icyqwq** [comment]
Added build instructions and cmake files for IDF.
