### ISSUE TITLE
RTC_BM8563.ino

### ISSUE THREAD

**Issue by hisshihit** [m5stack/M5EPD#8]
Is just the same RTC_BM8563.ino and RTC_WakeUp.ino ?

**Comment by uolot** [comment]
I compared both files using `diff` and they are exactly the same

**Comment by hisshihit** [comment]
Looking forward to upload correct RTC_WakeUp.ino(^^)

**Comment by OyczE** [comment]
yep also reported here:
https://forum.m5stack.com/post/11558
